# /etc/nsswitch.conf — Vajra OS Name Service Switch
passwd:     files systemd
group:      files systemd
shadow:     files
gshadow:    files

hosts:      files dns mdns4_minimal [NOTFOUND=return] myhostname
networks:   files

protocols:  db files
services:   db files
ethers:     db files
rpc:        db files

netgroup:   nis
